version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=students
      - MYSQL_ROOT_PASSWORD=password@123
    volumes:
      - "./:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p 'password' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  www:
    build: .
    volumes:
      - "./:/var/www/html"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=students
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
